/**
 * https://www.codewars.com/kata/5a331ea7ee1aae8f24000175
 * 
 * Disclaimer
 * 
 * This Kata is an insane step-up from Avanta's Kata, so I recommend to solve it first before trying this one.
 * Problem Description
 * 
 * A coloured triangle is created from a row of colours, each of which is red, green or blue. Successive rows, each containing one fewer colour than the last, are generated by considering the two touching colours in the previous row. If these colours are identical, the same colour is used in the new row. If they are different, the missing colour is used in the new row. This is continued until the final row, with only a single colour, is generated.
 * 
 * For example, different possibilities are:
 * 
 * Colour here:            G G        B G        R G        B R
 * Becomes colour here:     G          R          B          G
 * 
 * With a bigger example:
 * 
 * R R G B R G B B
 *  R B R G B R B
 *   G G B R G G
 *    G R G B G
 *     B B R R
 *      B G R
 *       R B
 *        G
 * 
 * You will be given the first row of the triangle as a string and its your job to return the final colour which would appear in the bottom row as a string. In the case of the example above, you would be given 'RRGBRGBB', and you should return 'G'.
 * Constraints
 * 
 * 1 <= length(row) <= 10 ** 5
 * 
 * The input string will only contain the uppercase letters 'B', 'G' or 'R'.
 * 
 * The exact number of test cases will be as follows:
 * 
 *     100 tests of 100 <= length(row) <= 1000
 *     100 tests of 1000 <= length(row) <= 10000
 *     100 tests of 10000 <= length(row) <= 100000
 * 
 * Examples
 * 
 * Kata.triangle("B") == 'B'
 * Kata.triangle("GB") == 'R'
 * Kata.triangle("RRR") == 'R'
 * Kata.triangle("RGBG") == 'B'
 * Kata.triangle("RBRGBRB") == 'G'
 * Kata.triangle("RBRGBRBGGRRRBGBBBGG") == 'G'
 */
public class CW_InsaneColouredTriangles {
	
	public static int[] convert(String palette) {
		int[] converted = new int[palette.length()];
		for(int i=0; i<palette.length(); i++) {
			if(palette.charAt(i) == 'R')
				converted[i] = 0;
			else if(palette.charAt(i) == 'G')
				converted[i] = 1;
			else if(palette.charAt(i) == 'B')
				converted[i] = 2;
		}
		return converted;
	}
	  
	static int nCrModpDP(int n, int r, int p) { 
		int[] C=new int[r+1]; 
		C[0] = 1; 
		for (int i = 1; i <= n; i++) { 
			for (int j = Math.min(i, r); j > 0; j--) 
				C[j] = (C[j] + C[j-1])%p; 
		} 
		return C[r]; 
	} 
	     
	static int nCrModpL(int n, int r, int p) { 
		if (r==0) 
			return 1;  
		int ni = n%p; 
		int ri = r%p;     
		return (nCrModpL(n/p, r/p, p) * nCrModpDP(ni, ri, p)) % p;
	} 
	  
	public static int compute(int[] pattern) {
		long sum = pattern[0];
		int len = pattern.length - 1;
		for(int i=1; i<=len; i++)
			sum = (sum + (nCrModpL(len, i, 3) * pattern[i]) % 3) % 3;
		if(pattern.length % 2 == 0)
			sum *= -1;
		return (int)((sum%3)+3)%3;
	}
	  
	  
	/**
	 * Test function for CodeWars.
	 * 
	 * @param row
	 * @return
	 */
	public static char triangle(final String row) {
		int ans = compute(convert(row));
		System.out.println(row);
		if(ans == 0) return 'R';
		else if(ans == 1) return 'G';
		else return 'B';
	}
	
	/**
	 * Main
	 */
	public static void main(String[] args) {
		System.out.println(triangle("RBRGBRBGGRRRBGBBBGG"));
	}
}